### PR TITLE
Removes unnecessary overriden fields of Album

### LINKED ISSUE #83: User's Following Artists api not working
The method .me.following(FollowingType.artist) is not working because when _parseBundledPage tries to create a new Page it cant calculate isLast because the APIs are not returning the offset.

### LINKED ISSUE #84: _$AlbumFromJson is not working when there is releaseDate
I see that the Album class is extending AlbumSimple and is overriding releaseDate and releaseDatePrecision without assigning the value to the superclass. The result of _$AlbumFromJson is so an Album with releaseDate and releaseDatePrecision equals null. 
I suggest removing the override from the Album class.

### PR DESCRIPTION
**Pull request by hayribakici**
This PR fixes #84 and removes the unnecessary fields of `Album`.

### CODE REVIEW

File: lib/src/models/album.dart [hunk 1]
```diff
@@ -100,9 +89,9 @@ class AlbumSimple extends Object {
   String releaseDate;
```
Comment (hayribakici) [inline lib/src/models/album.dart:89]: @rinukkusu should this not be a `Date` object? What do you think?

Comment (rinukkusu) [reply lib/src/models/album.dart:89]: You're right, but I don't know if `Date` can parse all these 3 "precisions" correctly.

> Depending on the precision, it might be shown as "1981" or "1981-12".

Can you please try it and check with the other 2 precisions in your test?

Comment (hayribakici) [reply lib/src/models/album.dart:89]: Yeah, it doesn't work. For `expect(album.releaseDate, DateTime(2012));` I get `FormatException: Invalid date format
2012`

Comment (rinukkusu) [reply lib/src/models/album.dart:89]: Sad 😄 
LGTM otherwise!

**Review by rinukkusu — APPROVED** [review]
