### PR TITLE
Feature/83 fix following artist

### LINKED ISSUE #83: User's Following Artists api not working
The method .me.following(FollowingType.artist) is not working because when _parseBundledPage tries to create a new Page it cant calculate isLast because the APIs are not returning the offset.

### PR DESCRIPTION
**Pull request by hayribakici**
This PR supports cursored pages to navigate pages through an `after` curser, rather than an `offset` and fixes #83 .

- Adds new object model `CursorPaging` 
- adds `user/me/following` unit test

### CODE REVIEW

File: lib/src/models/cursor_paging.dart [hunk 1]
```diff
@@ -0,0 +1,30 @@
+// Copyright (c) 2020, hayribakici. All rights reserved. Use of this source code
+// is governed by a BSD-style license that can be found in the LICENSE file.
+
+part of spotify.models;
+
+// typedef ParserFunction<T> = T Function(dynamic object);
+
+// Iterable<dynamic> itemsNativeFromJson(List<dynamic> json) => json;
+// List<Map> itemsNativeToJson(Iterable<dynamic> items) => List.from(items);
```
Comment (rinukkusu) [inline lib/src/models/cursor_paging.dart:9]: Do we still need these?

File: lib/src/endpoints/endpoint_paging.dart [hunk 2]
```diff
@@ -44,7 +51,31 @@ class Page<T> {
...
+  /// Abstract method that is used to do the api call and json serializing
+  Future<T> getPage(int limit, int offset);
+}
+
+mixin CursorStrategy<T> {
+  Future<T> first([int limit = defaultLimit]) => getPage(limit);
+
+  /// Abstract method that is used to do the api call and json serializing
+  Future<T> getPage(int limit, [String after = '']);
+}
```
Comment (rinukkusu) [inline lib/src/endpoints/endpoint_paging.dart:76]: Very nice! :)

**Review by rinukkusu — COMMENTED** [review]
LGTM so far - thanks for adding this feature, this will help us a lot!! 🚀

**Review by rinukkusu — APPROVED** [review]
